import { Divider, YoutubeVideo, ImageSlideshow, MakeLink, LeftContentRightText1, LeftContentRightTextHalf, MakeTitle, MakeTitleMedium, MakeTitleSmaller, MakeVideo, MakeInternalLink } from './Utils'
import ReflectionInterfaceImage from './../resources/reflectionsystem/int_reflect_interface.png'
import ReflectExampleImage from './../resources/reflectionsystem/reflectexample2.png'
import InspectorExampleImage from './../resources/reflectionsystem/autoinspector.png'
import CustomStructImage from './../resources/reflectionsystem/reflectcustomstruct.png'
import CustomStructCodeImage from './../resources/reflectionsystem/reflectcustomstructcode.png'
import AutoGeneratedNodesImage from './../resources/reflectionsystem/autogeneratednodes.png'
import AutoSerializationImage from './../resources/reflectionsystem/autoserialization.png'

function ReflectionSystem() {
    return (
        <div className='md:max-w-6xl md:mx-auto text-left px-10'>
            <div className='pt-10' />
            <MakeTitle text="REFLECTION SYSTEM" />
            <div className='max-w-md mx-auto pb-8'>
                <p className='pt-10'>A homemade reflection system built with the intent to save a lot of time for me and other programmers. Easy of use was also a high priority.</p>
            </div>

            <Divider />

            <div className='lg:flex lg:flex-row lg:gap-x-6 py-6'>
                <div className='lg:basis-2/3'>
                    <img className='mx-auto p-4' src={ReflectionInterfaceImage} />
                    <br />
                    <p>This is the interface for reflecting an int. When creating a new reflector, one simply has to implement the functions one need.</p>
                </div>
                <div className='lg:basis-1/3'>
                    <MakeTitleSmaller text="BUILT USING VISITOR PATTERN" />
                    <p>The reflection system is built using visitor pattern where each type we can reflect on is visitable.</p>
                    <p>It is very powerful and some nice systems and features has been built using it. Read more below!</p>
                    <p>Note that being a visitor pattern, performance issues will arise at some point, we have not reached that point yet though.</p>
                </div>
            </div>

            <Divider />

            <MakeTitleMedium text="SYSTEMS BUILT USING THE RELFECTION SYSTEM" />

            <div className='max-w-md mx-auto pb-8'>
                <p className='pt-10'>The below showcases show images and examples made by reflecting what is shown in this image below.</p>
                <img src={ReflectExampleImage} />
            </div>

            <LeftContentRightText1 image={InspectorExampleImage}>
                <MakeTitleSmaller text="EXPOSE VARIABLES IN INSPECTOR" />
                <p>A programmer can with 1 line of code expose a variable into the inspector that is now viewable and modifyable.</p>
            </LeftContentRightText1>

            <LeftContentRightText1 image={CustomStructImage}>
                <MakeTitleSmaller text="SUPPORTS ARRAYS AND CUSTOM TYPES" />
                <p>A more common example would look like this that has reflected types within each other and arrays with some nice header and separators.</p>
                <img src={CustomStructCodeImage} />
            </LeftContentRightText1>

            <LeftContentRightText1 image={AutoGeneratedNodesImage}>
                <MakeTitleSmaller text="AUTO-GENERATED VISUAL SCRIPT NODES" />
                <p>Nodes for the visual scripting are for each component that is reflected is automatically generated to easily get or set component values within the visual script.</p>
            </LeftContentRightText1>

            <LeftContentRightText1 image={AutoSerializationImage}>
                <MakeTitleSmaller text="AUTOMATIC SERIALIZATION/DESERIALIZATION" />
                <p>Automatically serialized based on all the reflected values, can also easily change serialization method because it uses a generic interface. If we wanted binary serialization, we need just implement an interface.</p>
            </LeftContentRightText1>

            <div className='lg:flex lg:flex-row lg:gap-x-6 py-6'>
                <div className='lg:basis-2/3'>
                    <MakeTitleSmaller text="AUTOMATIC RESOURCE REFERENCES HANDLING" />
                    <p>When saving the scene, a list of resources gets written of all the resources that are reflected in each component to easily know what resource to load when loading a scene. This opens up the ability to load all the resources immediately on separate threads while loading other stuff from the scene simultanously.</p>
                </div>
                <div className='lg:basis-1/3'>
                    <MakeTitleSmaller text="GAMEOBJECT PREFAB SYSTEM" />
                    <p>GameObject prefabs are also built upon this reflection system, you can <MakeInternalLink to="/editor">read more about it on the editor page.</MakeInternalLink></p>
                </div>
            </div>
        </div>
    );
}

export default ReflectionSystem;